### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by jvanvorst** [cyrusbehr/sdk_design#2]
Hi Cyrus.  Following the build procedure I got this error:

$ cmake ..
CMake Error at CMakeLists.txt:82 (add_executable):
  The target name "test" is reserved or not valid for certain CMake features,
  such as generator expressions, and may result in undefined behavior.

CMake Error at CMakeLists.txt:83 (target_link_libraries):
  Cannot specify link libraries for target "test" which is not built by this
  project.

-- Configuring incomplete, errors occurred!

Any ideas?

**Comment by cyrusbehr** [comment]
@jvanvorst Thanks for bringing this to my attention. It looks like cmake 3.10 and before always reserve the `test` target name, whereas newer version don't (which I was using). It is described in more detail [here](https://cmake.org/cmake/help/v3.18/policy/CMP0037.html).

I'll push a fix for this.
